### ISSUE TITLE
[HW10] Bash скрипты (переменые, перенаправление, циклы)

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#10]
**Дедлайн: 21/08/2023**<br /><br />1. Создать Bash скрипт `print-value.sh`, выводящий значение переменной `$VALUE` в консоль. Выполнить скрипт 3 раза, передавая каждый раз значение этой переменной разным способом.<br />2. Создать **Shell** скрипт `check-parity-shell.sh`, который принимает число в качестве первого аргумента командной строки, и для чётного числа выводит в консоль строку "чётное", а для нечётного - "нечётное". В случае, если переданный аргумент не является числом, вывести соответствующее сообщение и завершить скрипт с кодом 1.<br />3. Переписать скрипт из предыдущего задания на Bash и назвать его `check-parity-oneline.sh` таким образом, чтобы он не использовал конструкцию `if ... then ... else .. fi`.<br />4. Создать Bash скрипт `not-empty-file.sh`, который считывает из `STDIN` имя файла и выводит в `STDOUT` его имя в случае, если он не является пустым. Проверить работу файла при помощи команды `ls | ./not-empty-file.sh | xargs wc -l`.<br />5. Создать скрипт `generate-testing-matrix.sh`, в котором объявляется 2 массива (`os` - массив операционных систем и `arch` - массив архитектур процессора) и который выводит в консоль комбинации всех возможных пар `<OS>-<ARCH>`. Например, `linux-x86`, `linux-amd64`, и т.д.<br />6. Обновить файл `.github/workflows/validate-shell.yaml`, если он не совпадает с https://github.com/tms-dos17-onl/_sandbox/blob/main/.github/workflows/validate-shell.yaml.<br />7. Создать Pull Request (PR) содержащий 5 созданных скриптов.<br />8. (\*\*) Убедиться, что **все** файлы в репозитории проходят валидацию.<br /><br />_\*\* не обязательны к выполнению. Задачи на интерес_

**Comment by Alex777888777** [comment]
@AlexPykavy Добрый, не могу понять суть 4 задания можете пояснить по другому. Я так написал скрипт, но он по худу не правильный

**Comment by AlexPykavy** [comment]
Привет, нужно было считывать имя/имена файлов из /dev/stdin и проверять их на пустоту, типа https://stackoverflow.com/a/7045517

**Comment by Alex777888777** [comment]
@AlexPykavy Сделал. Но не смог разобраться почему не проходит валидация

**Comment by Alex777888777** [comment]
@AlexPykavy Добрый ,сделал
