### ISSUE TITLE
[HW14] Сертификаты TLS

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#18]
**Дедлайн: 07/09/2023**<br /><br />1. Сгенерировать пару ключей/сертификатов (`private.pem` и `public.pem`) при помощи OpenSSL.<br />2. Создать скрипт `encrypt.sh`, который считывает стандартный поток ввода, шифрует его при помощи `public.pem` через OpenSSL и выводит в стандартный поток вывода.<br />3. Создать скрипт `decrypt.sh`, который считывает стандартный поток ввода, расшифровывает его при помощи `private.pem` через OpenSSL и выводит в стандартный поток вывода.<br />4. Сгенерировать публичный сертификат `public-nginx.pem` для `private.pem` через OpenSSL, используя `<LASTNAME>.io` в качестве Common Name (CN).<br />5. Настроить Nginx на работу по HTTPS, используя сертификаты из предыдущего задания. Например, чтобы Nginx возвращал домашнюю страницу по HTTPS.<br />6. Настроить доверие публичному сертификату в браузере и проверить это.<br />7. А теперь открыть домашнюю страницу Nginx по HTTPS через `curl` не прибегая к опции `-k`.

**Comment by Alex777888777** [comment]
@AlexPykavy Сделал,и можете посмотреть 10 домашуку, а то я там все исправил, а она уже весит много недель.

**Comment by AlexPykavy** [comment]
У тебя в 10-й был merge конфликт:
![image](https://github.com/tms-dos17-onl/Alex-Krylov/assets/32162928/948d2f16-6565-4865-9fea-e3233278812f)

Я его сам исправил и замержил.

**Comment by AlexPykavy** [comment]
По этой домашке всё ок. Не совсем понял, зачем ты сделал 2 варианта encrypt/decrypt, но это не сильно важно)
