### ISSUE TITLE
[HW15] БД

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#19]
**Дедлайн: 14/09/2023**<br /><br />1. Установить MySQL на VM.<br />2. (\*\*) Настроить Multi-Primary репликацию для MySQL на 2 VM согласно [инструкции](https://www.vultr.com/docs/configure-mysql-group-replication-on-ubuntu-20-04/).<br />3. Создать схему БД `clinic` и наполнить её данными используя скрипты из https://github.com/tms-dos17-onl/_sandbox/tree/main/lecture18/mysql/initdb.d/data.<br />4. Создать бэкап базы данных `clinic`.<br />5. Написать следующие SQL запросы:<br />    - Вывести всех врачей, работающих в терапевтическом отделении.<br />    - Вывести в каких отделениях побывал каждый пациент.<br />    - Обновить дату приёма для пациента Ивана Иванова на 2022-02-09.<br />    - Удалить врача Андрея Быкова и все его приёмы.<br />    - Добавить нового врача Фила Ричардса и новую пациентку Василису Васильеву и записать её к Филу Ричардсу на приём на 2022-02-14.<br />6. Восстановить базу данных `clinic` из бэкапа и проверить, что данные соответствуют состоянию базы данных до внесенных в предыдущем задании изменений.<br />7. Установить MongoDB<br />8. Создать БД `clinic` и наполнить её данными используя скрипты из https://github.com/tms-dos17-onl/_sandbox/tree/main/lecture18/mongo/initdb.d.<br />9. Написать выборочно 3 запроса из задания 5 для MongoDB используя `mongosh` команды.<br /><br />_\*\* не обязательны к выполнению. Задачи на интерес_

**Comment by Alex777888777** [comment]
@ Done/!

**Comment by AlexPykavy** [comment]
В запросе "Вывести всех врачей, работающих в терапевтическом отделении" желательно использовать JOIN'ы. Но считаю это некритичным, так что принимается)
