### ISSUE TITLE
[HW17] Ansible (роли)

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#21]
**Дедлайн: 26/09/2023**<br /><br />Реализовать Ansible playbook, который:<br />1. Устанавливает LAMP стэк на VM **при помощи ролей**:<br />    - [Apache](https://galaxy.ansible.com/geerlingguy/apache)<br />    - [MySQL](https://galaxy.ansible.com/geerlingguy/mysql)<br />    - [PHP](https://galaxy.ansible.com/geerlingguy/php)<br />2. (\*\*) Устанавливает memcached сервис на VM при помощи [роли](https://galaxy.ansible.com/geerlingguy/memcached)<br />3. Перенести логику по установке приложения https://github.com/qyjohn/simple-lamp в Ansible роль.<br />4. Создать Pull Request (PR) содержащий Ansible playbook и разработанную роль/роли.<br /><br />_\*\* не обязательны к выполнению. Задачи на интерес_

**Comment by Alex777888777** [comment]
@AlexPykavy  Сделано

**Comment by AlexPykavy** [comment]
Выглядит окей, молодец, даже свои роли написал)

Заметил, кстати, ещё один нюанс, который в прошлый домашке упустил: ты делаешь chmod через shell команду, а это не рекомендуется, поскольку shell и command команды не являются идемпотентными и повторное их выполнение может вызывать проблемы. Лучше используй  ansible.builtin.file модуль.

А можешь, пожалуйста, ещё попробовать заиспользовать роли из Ansible Galaxy, что я указал в Issue? И нужно сделать так, чтобы они были описаны в requirements.txt, а не просто скачаны. Можешь посмотреть работу Стаса или Владимира, как пример. Свои роли оставь, они никому мешать ну будут, просто playbook_roles.yaml будет ссылаться на другие

**Comment by Alex777888777** [comment]
И нужно сделать так, чтобы они были описаны в requirements.txt, а не просто скачаны.

**Comment by AlexPykavy** [comment]
Вот такой [файлик](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file) нужно было создать, вместо того, чтобы качать все роли вручную.

**Comment by Alex777888777** [comment]
Да, можно закрывать.Я вроде понял, что за оно
