### ISSUE TITLE
[HW3] Проверка состояния ресурсов системы

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#3]
**Дедлайн: 21/07/2023**<br /><br />1. Создать bash-скрипт собирающий данные о количестве свободной памяти, текущей загрузке процессора, ip-адрес, вывести в формате «Ключ: значение», причем все ключи заменить на русские названия, например чтобы вместо «Mem: 1024Mb» получалось «Память: 1024Мб», для приведения к нужному формату использовать grep, sed и awk.<br />2. Написать bash-скрипт который создает пользователя (принимает имя в качестве первого аргумента) и создает в его домашней директории файл с информацией о системе: Ядро, CPU, RAM, Дисковая подсистема (lscpu, lsblk, uname, etc). Вывод каждой команды должен быть отделен сепаратором (например ====)<br />3. (\*\*) Cоздать файл immortalfile, запретить удаление файла даже пользователем root и попытаться его удалить из под root, результатом должно быть “Operation not permitted”. Подсказка: CHATTR(1)<br />4. (\*\*\*) Выполнить команду, разобраться что она делает и что сохраняется в file.log<br /><br />    `env -i bash -x -l -c 'echo hello_there!' > file.log 2>&1`<br /><br />_\*\* и \*\*\* не обязательны к выполнению. Задачи на интерес_

**Comment by Alex777888777** [comment]
@AlexPykavy  Сделал домашку

**Comment by AlexPykavy** [comment]
Мне кажется, что я тебя запутал с Markdown форматом. Этот формат используется для оформления файлов документов (не скриптов!). Например, чтобы создавать `Readme.md`. Скрипты должны иметь другие расширения. Например, Shell/Bash скрипты должны иметь расширение `.sh`.

Логика первого скрипта очень интересная: он вышел интерактивным 😀Но форматирование его оставляет желать лучшего. Советую установить Visual Studio Code, а потом расшерение shell-format. Это позволит делать автоформатирование скриптов при помощи горячих клавиш `Alt + Shift + F`, чтобы они были более читаемыми.

Итого, тебе нужно:
- Установить Visual Studio Code, а потом расшерение shell-format
- Создать 2 скрипта с расширениями `.sh` и дать им понятные названия, чтобы было понятно что они делают. Например, первый можно назвать `show_system_info.sh`.
- Создать `Readme.md` с выводом работы скриптов и кратким описанием того, что ты сделал.

**Comment by Alex777888777** [comment]
@AlexPykavy  Исправил

**Comment by AlexPykavy** [comment]
Отлично! Стало намного лучше)

Это задание мы закрываем, но есть несколько комментариев на будущее:
- видимо, ты не устанавил shell-format или не сделал автоформатирование с помощью `Alt + Shift + F`, потому что видно, что в отступах в первом скрипте разное кол-во пробелов.
- во втором скрипте нужно было принимать имя пользователя как первый аргумент скрипта (например, [вот так](https://www.futurelearn.com/info/courses/linux-for-bioinformatics/0/steps/202962)).
