### ISSUE TITLE
[HW25] CI (знакомство)

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#34]
**Дедлайн: 09/11/2023**<br /><br />1. Прочитать [статью](https://martinfowler.com/articles/continuousIntegration.html).<br />2. Установить Jenkins.<br />3. Создать свой первый pipeline по [инструкции "Through the classic UI"](https://www.jenkins.io/doc/book/pipeline/getting-started/#through-the-classic-ui)

**Comment by Alex777888777** [comment]
@AlexPykavy Сделал!

**Comment by AlexPykavy** [comment]
Красавчик 😎
