### ISSUE TITLE
[HW28] CI (альтернативы Jenkins)

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#38]
**Дедлайн: 26/11/2023**<br /><br />1. Зарегестрироваться на любой облачной CI платформе (например BitBucket, GitLab, GitHub).<br />2. Реализовать pipeline для проекта [spring-petclinic](https://github.com/tms-dos17-onl/spring-petclinic), который состоит из следующих этапов (stages):<br />    - Clone<br />        - Клонируется данный проект. Обратите внимание, что этот репозиторий приватный и для того, чтобы его склонировать нужно использовать какие-то credentials.<br />    - Build<br />        - Происходит сборка проекта через Maven или Gradle и запускаются юнит-тесты.<br />    - Publish<br />        - Публикуется отчёт тестирования.<br />    - Notification<br />        - Отправляется письмо с результатом сборки, тому кто её запустил.

**Comment by Alex777888777** [comment]
@AlexPykavy Наконец сделал, сложно было. Но есть нюанс, в github Action нет прямой пересылки на email.Варианты bash пересылки с sendmail не прошли.
Вариант:
  server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build Status: ${{ job.status }} on ${{ github.repository }}
          body: |
            The build ${{ job.status }} for ${{ github.repository }} on branch ${{ github.ref }}.
            Commit: ${{ github.sha }}.
            Commit message: ${{ github.event.head_commit.message }}.
          to: youremail@example.com 
          Тоже нет там надо точно знать кому, как и на slack.Тоесть чтобы переслать, нужно иметь много данный о том кто запускает. А чтобы это слалось любому я не знаю как.

**Comment by AlexPykavy** [comment]
Молодец! Нашел хороший способ как обойти проблему с падающими тестами.

Правда, некоторые моменты можно было и упростить. Например, вместо
```
docker build -t maven - <<EOF
FROM maven:3.8.4-openjdk-17
EOF
docker run -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven bash -c "mvn clean install && ./mvnw test"
```
можно было использовать
```
docker run -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.8.4-openjdk-17 bash -c "mvn clean install && ./mvnw test"
```

А насчёт уведомлений, думаю, что можно пропустить, раз так много параметров нужно указать
