### ISSUE TITLE
[HW31] GCP (Storage & VM autoscaling)

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#41]
**Дедлайн: 05/12/2023**<br /><br />1. Работа с Google Cloud Storage (GCS):<br />    - Создать GCE, открыть SSH сессию в созданную VM.<br />    - Cклонировать [репозиторий](https://github.com/bezkoder/google-cloud-storage-nodejs-upload-file) и ознакомиться с проектом и [инструкцией](https://www.bezkoder.com/google-cloud-storage-nodejs-upload-file/) к нему.<br />    - Создать необходимые ресурсы для работы приложения:<br />        - Создать GCS Bucket `<LASTNAME>-gcs-demo`.<br />        - Создать Service Account `<LASTNAME>-gcs-demo` и назначьте ему роль `Storage Object Admin` (`IAM & Admin -> IAM -> GRANT ACCESS`)<br />        - Сгенерировать и скачать Service Account Key в формате JSON.<br />    - [Установить Node.js 18](https://github.com/nodesource/distributions).<br />    - Установить зависимости приложения через NPM.<br />    - Поправить имя GCS Bucket и имя файла с Service Account Key в каком-то из .js файлов приложения.<br />    - Запустить приложение и проверить его работоспособность путем выполнение нескольких HTTP запросов через Postman как описано в [Node.js upload File to Google Cloud Storage example параграфе](https://www.bezkoder.com/google-cloud-storage-nodejs-upload-file/#Nodejs_upload_File_to_Google_Cloud_Storage_example).<br />2. Настройка автомасштабирования:<br />    - Создать шаблон виртуальной машины `apache-php-template`:<br />        - Активировать Allow HTTP traffic.<br />        - В качестве startup скрипта написать команды для установки Apache веб-сервера с поддержкой PHP и создания phpinfo страницы (`<?php phpinfo(); ?>`).<br />    - Создать группу виртуальных машин `apache-php-group` с помощью шаблона `apache-php-template`:<br />        - Использовать мультизональную локацию.<br />        - Настроить автомасштабирование от 2 до 4 экземпляров.<br />        - Понизить порог для автомасштабирования до 30% CPU.<br />    - Создать Application Load Balancer:<br />        - В качестве Backend использовать ранее созданную группу VM `apache-php-group`:<br />            - Выключить Cloud CDN.<br />            - В качестве, Health Check использовать просто проверку доступности домашней страницы Apache.<br />    - Проверить распределение трафика путем выполнения HTTP запроса `GET /index.php` через Load Balancer и сравнения свойства `SERVER_ADDR` в phpinfo таблице.<br />    - Сгенерировать нагрузку на Load Balancer и убедиться, что работает автомасштабирование.

**Comment by Alex777888777** [comment]
@AlexPykavy Сделал

**Comment by AlexPykavy** [comment]
Принимается! Но есть вопрос: как ты определил, что Load Balancer распределяет трафик между машинами в Instance Group?

**Comment by Alex777888777** [comment]
@AlexPykavy Там же две фотки и я указал в красном кружочке, что если часто нажимаю обновить меняются инстансы
