### ISSUE TITLE
[HW7] Работа с Git

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#7]
**Дедлайн: 07/08/2023**<br /><br />1. Вывести список всех удаленных репозиториев для локального.<br />2. Вывести список всех веток.<br />3. Вывести последние 3 коммитa с помощью `git log`.<br />4. Создать пустой файл `README.md` и сделать коммит.<br />5. Добавить фразу "Hello, DevOps" в `README.md` файл и сделать коммит.<br />6. Сделать реверт последнего коммита. Вывести последние 3 коммитa с помощью `git log`.<br />7. Удалить последние 3 коммита с помощью `git reset`.<br />8. Вернуть коммит, где добавляется пустой файл `README.md`. Для этого найти ID коммита в `git reflog`, а затем сделать cherry-pick.<br />9. Удалить последний коммит с помощью `git reset`.<br />10. Переключиться на ветку `main` или `master`. Если ветка называется `master`, то переименовать её в `main`.<br />11. Скопировать файл https://github.com/tms-dos17-onl/_sandbox/blob/main/.github/workflows/validate-shell.yaml, положить его по такому же относительному пути в репозиторий. Создать коммит и запушить его в удаленный репозиторий.<br />12. Создать из ветки `main` ветку `develop`. Переключиться на неё и создать `README.md` в корне репозитория. Написать в этом файле какие инструменты DevOps вам знакомы и с какими вы бы хотели познакомиться больше всего (2-3 пункта).<br /><br />> :warning: **Для выполнения задания использовать Markdown, а именно заголовок и списки**<br /><br />13. Создать из ветки `main` ветку `support` и создать там файл `LICENSE` в корне репозитория с содержимым https://www.apache.org/licenses/LICENSE-2.0.txt. Создать коммит. Вывести последние 3 коммитa.<br />14. Переключиться обратно на ветку `main` и создать там файл `LICENSE` в корне репозитория с содержимым https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt. Создать коммит. Вывести последние 3 коммитa.<br />15. Сделать merge ветки `support` в ветку `main` и решить конфликты путем выбора содержимого только одной лицензии.<br />16. Переключиться на ветку `develop` и сделать rebase относительно ветки `main`.<br />17. Вывести историю последних 10 коммитов в виде графа с помощью команды `git log -10 --oneline --graph`.<br />18. Запушить ветку `develop`. В истории коммитов должен быть мерж `support -> main`.<br />19. Зайти в свой репозиторий на GitHub и создать Pull Request из ветки `develop` в ветку `main`.

**Comment by Alex777888777** [comment]
@AlexPykavy Сделал. Но так и  не разобрался в разнице rebase и merge . Допустим у нас две ветки  A,B , нахожусь в B чего-тот там делаю и хочу внести изменения из A ко мне, как бы дополняю. Я пишу git rebase A, посмотрел делаю дальше ,но ведь можно сделать merge A, и я их объединяю получается тот же результат.

**Comment by AlexPykavy** [comment]
Ты всё правильно понимаешь: конечное состояние файлов будет таким же, а вот истории изменений будут разными. Представим, что у нас есть 2 ветки:
```
(main)    A -> B -> C -> D -> E
(develop) A -> B -> C -> F -> G
```

Есть такое правило:
- в основную ветку (`main` в нашем случае), изменения из других веток делаются при помощи `merge`.
- в другие ветки (`develop` в нашем случае), изменения из `main` подтягиваются при помощи `rebase`.

Если мы делаем `merge develop -> main`, то в итоге получаем:
```
(main) A -> B -> C -> D -> E -> F -> G
```

Если мы делаем `rebase develop <- main`, то в итоге получаем:
```
(develop) A -> B -> C -> D -> E -> F -> G
```
а если мы делаем `merge main -> develop`, то в итоге получаем:
```
(develop) A -> B -> C -> F -> G -> D -> E
```
То есть мы или свои коммиты из ветки `develop` (`F`, `G`) будем применять поверх коммитов из `main`, или же коммиты из `main` (`D`, `E`) применять поверх своих. И здесь кроется очень важный нюанс в случае, когда возникают конфликты. Мы или их решаем для своих коммитов, если делали `rebase`, или для чужих коммитов из ветки `main`. Иными словами, нам нужно поменять чужие коммиты так, чтобы она работали не с тем, что предполагалось в `main`, а уже с тем, что мы поменяли.

**Comment by AlexPykavy** [comment]
По домашке всё окей! Есть один нюанс с validate-shell.yaml файликом, что ты положил: ты сделал опечатку в названии папки `.github`.

**Comment by Alex777888777** [comment]
Я не знал как изменить в настройках. Так что открыл код через F12  и поправил там
