### ISSUE TITLE
[HW8] Настройка доступа, репликация папок и мониторинг

### ISSUE THREAD

**Issue by AlexPykavy** [tms-dos17-onl/Alex-Krylov#8]
**Дедлайн: 14/08/2023**<br /><br />1. Вывести в консоль список всех пользователей системы.<br />2. Найти и вывести в консоль домашние каталоги для текущего пользователя и root.<br />3. Создать Bash скрипт `get-date.sh`, выводящий текущую дату.<br />4. Запустить скрипт через `./get-date.sh` и `bash get-date.sh`. Какой вариант не работает? Сделать так, чтобы оба варианта работали.<br />5. Создать пользователей **alice** и **bob** с домашними директориями и установить `/bin/bash` в качестве командной оболочки по умолчанию.<br />6. Запустить интерактивную сессию от пользователя **alice**. Создать файл `secret.txt` с каким-нибудь секретом в домашней директории при помощи текстового редактора `nano`.<br />7. Вывести права доступа к файлу `secret.txt`.<br />8. Выйти из сессии от **alice** и открыть сессию от **bob**. Вывести содержимое файла `/home/alice/secret.txt` созданного ранее не прибегая к команде `sudo`. В случае, если это не работает, объяснить.<br />9. Создать файл `secret.txt` с каким-нибудь секретом в каталоге `/tmp` при помощи текстового редактора `nano`.<br />10. Вывести права доступа к файлу `secret.txt`. Поменять права таким образом, чтобы этот файл могли читать только владелец и члены группы, привязанной к файлу.<br />11. Выйти из сессии от **bob** и открыть сессию от **alice**. Вывести содержимое файла `/tmp/secret.txt` созданного ранее не прибегая к команде `sudo`. В случае, если это не работает, объяснить.<br />12. Добавить пользователя **alice** в группу, привязанную к файлу `/tmp/secret.txt`.<br />13. Вывести содержимое файла `/tmp/secret.txt`.<br />14. Скопировать домашнюю директорию пользователя **alice** в директорию `/tmp/alice` с помощью `rsync`.<br />15. Скопировать домашнюю директорию пользователя **alice** в директорию `/tmp/alice` на другую VM по SSH с помощью `rsync`. Как альтернатива, можно скопировать любую папку с хоста на VM по SSH.<br />16. Удалить пользователей **alice** и **bob** вместе с домашними директориями.<br />17. С помощью утилиты `htop` определить какой процесс потребляет больше всего ресурсов в системе.<br />18. Вывести логи сервиса Firewall с помощью `journalctl` не прибегая к фильтрации с помощью `grep`.

**Comment by Alex777888777** [comment]
@AlexPykavy  Сделал

**Comment by Alex777888777** [comment]
Единственное, что плохо понял это Firewall.Если пишу sudo ufw status "inactive" то есть неактивен, тогда как может выводить логи?  Брендмауер  на Ubuntu это - netfilter встроенный в ядро и пользуюсь я которым через iptables ,но их логи я не нашел

**Comment by AlexPykavy** [comment]
Мне кажется, что сам Firewall (ufw) неактивен, а вот сам сервис обертка (/lib/systemd/system/ufw.service) активен. У меня такая же ситуация.
```
user@PLL-ALEXA-PYKAV:~$ sudo ufw status
Status: inactive
user@PLL-ALEXA-PYKAV:~$ systemctl status ufw
● ufw.service - Uncomplicated firewall
     Loaded: loaded (/lib/systemd/system/ufw.service; enabled; vendor preset: enabled)
     Active: active (exited) since Sun 2023-08-13 11:38:21 CEST; 1h 33min ago
       Docs: man:ufw(8)
    Process: 111 ExecStart=/lib/ufw/ufw-init start quiet (code=exited, status=0/SUCCESS)
   Main PID: 111 (code=exited, status=0/SUCCESS)

Aug 13 11:38:21 PLL-ALEXA-PYKAV systemd[1]: Starting Uncomplicated firewall...
Aug 13 11:38:21 PLL-ALEXA-PYKAV systemd[1]: Finished Uncomplicated firewall.
user@PLL-ALEXA-PYKAV:~$
```

**Comment by AlexPykavy** [comment]
Замечаний по домашке нет. Всё сделано хорошо. Принимается!
